services:
  postgres:
    container_name: postgres_container
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: bananaback
      POSTGRES_PASSWORD: password
      POSTGRES_DB: banana_db
    volumes:
      - postgres:/var/lib/postgresql/data # Use a named volume for persistence
    ports:
      - '5432:5432'
    restart: unless-stopped

  spring-app:
    container_name: spring_app_container
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/banana_db
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres:

